version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes: 
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    env_file:
      - .env.production

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: squirel_backend:latest
    container_name: squirel_backend
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db_data: