name: deploy workflow

on: [push]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 18.x
          cache: 'npm'
      
      - name: Install dependencies for web
        run: npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #build docker image
      - name: create docker image
        run: docker compose build
      #recreate a .env file with secretes

      # create a volume with .env for back to use

      #connect to vps with ssh
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Send backend image to hub
        run: docker push myusername/squirel_backend:latest

      #connect to vps with ssh
      - name: connect to vps and pull docker image
        uses: appleboy/ssh-action@v0.1.10
        with: 
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script:  |
            docker pull myusername/squirel_backend:latest
            # Add your deployment commands here
            echo "Image pulled successfully!"

      

      

      
      #

